### ISSUE TITLE
Translation to German

### ISSUE THREAD

**Issue by JBlumenberg** [mephitrpg/arkham-iii-monsters#1]
Thanks for your great app. Would it be possible to have a German version as well? I can provide all necessary translations.

**Comment by mephitrpg** [comment]
Hi, I just sent you an email, thanks!

**Comment by mephitrpg** [comment]
@JBlumenberg are you still interested?

**Comment by Vortilion** [comment]
PR for german translation is pending.

**Comment by mephitrpg** [comment]
web version published, Android version is waiting for approval. Thank you!

**Comment by mephitrpg** [comment]
web version published, Android version is waiting for approval. Thank you!
