### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Faustoos** [mephitrpg/arkham-iii-monsters#2]
Hello, I made the french translation, need access to push ;)

**Comment by mephitrpg** [comment]
Thank you! Please make a pull request, or send me the files, thanks!

**Comment by mephitrpg** [comment]
HI @Faustoos , if you'd like to contribute I published a new app https://github.com/mephitrpg/arkham-iii-mythos-cup ;)

**Comment by Faustoos** [comment]
Seems to be good, first time for me  ; )

I didn't compile and test this time, just fork create branch push files and
made the merge request.

Hope its all good, give me a feedback please

Le mar. 12 avr. 2022 22:43, Jure di Mephit ***@***.***> a
écrit :

**Comment by mephitrpg** [comment]
I can't see the pull request 😅
